### ISSUE TITLE
Easily editable 'White list' and 'Delayed start list'

### ISSUE THREAD

**Issue by tnilzon** [gilgol2016/auto-overlay-remover#6]
I would be very nice to be able to edit the 'White list' and 'Delayed start list' in the options page. As it is now the lists are displayed, but not editable (the only way is with right click on the extension toolbar icon, but it is only for adding new domains).

So, editing in the options page would be most convenient.

/Thanks
tnilzon

**Comment by gilgol2016** [comment]
Dear tnilzon,
Thanks for writing me your comment / idea.

There is no enable editing till now, because it could cause the extension to collapse, in some scenarios. When I'll find a solution for it, I'll update and upload in the next version.

**Comment by tnilzon** [comment]
Great, thanks!
